### ISSUE TITLE
How to generate?

### ISSUE THREAD

**Issue by boelle** [KammutierSpule/kicad3Dmodels#1]
How would a dummie generate a wrl for a given value resistor?

do i use QT to run the generator?

**Comment by KammutierSpule** [comment]
For a dummie, you may look for pre generated values
https://github.com/KammutierSpule/kicad3Dmodels/tree/master/generated/Resistors
If you get lucky you will find already the values you need.

If you do not find your values and want go "for a beginner", you may manually create your WRL file
changing just the right digits of the ring "Inline { url “…/ring_1.wrl” }"
Have a look at:
https://forum.kicad.info/t/i-created-a-new-kicad3dmodels-library/5151/5?u=kammutierspule

If you want go expert, you will need to understand the source code and generator method. then using QTcreator to build the application.

Mind that the generator is not doing nothing more than an automation of something that can be easily performed manually. So you will need to understand the basics of the WRL

**Comment by boelle** [comment]
hehe.... i do want to go for "beginner" but i dont want to do it manual

i think i will have  a go at the QTcreator as doing it manual is not an easy way for me... i used the word dummie as i really am a dummie. :-P

i'm so much an dummie that i would prefer a website where i can just enter the value and download an wrl file :-D

**Comment by boelle** [comment]
hmm i might understand it

i see ring 0-11 which has a color each, now i just need to figure how  i build up a series of rings on a resistor

**Comment by KammutierSpule** [comment]
This project is a command line generator (no Graphic User Interface)
You only need to build and run it if you want to develop the / to the project (i.e edit for personal uses or expand and contribute to this project) So it was meant to be used by experts.

other way you may find the pre-generated files or if you cannot find what you looking for you can left a request for new components.

**Comment by boelle** [comment]
it was the zip with the pre-generated i could not find.... 

https://github.com/KammutierSpule/kicad3Dmodels/blob/master/generated/Resistors/kicad3Dmodels-Resistors-Film_Carbon-v0.1.1.zip

will have a go at that one.... if @bobc does not beat me to it with some kind of windows tool
